version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    groups:
      npm:
        update-types: [minor, patch]

  - package-ecosystem: terraform
    directories:
      - /bootstrap
      - /infra
    schedule:
      interval: weekly
    groups:
      terraform:
        update-types: [minor, patch]
